### ISSUE TITLE
Tracking for integration testing

### ISSUE THREAD

**Issue by gnunicorn** [effektio/effektio#2]
For testing our components, ideally the entire UI, we want an integration testing system on our  CI/CD for the flutter Android App.

The steps are:

- [x] basic [docker compose](https://github.com/matrix-org/synapse/blob/develop/contrib/docker/docker-compose.yml)
- [x] CI job with android emulator 
- [x] generate example data ( [via complement?](https://github.com/matrix-org/complement)] -- _we currently have mock data_
- [x] integration tests run on CI on android emulator

----

Are you able to do this? And want to earn some money while contributing here on Github? We have a bounty open for this issue:

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=109316302)](https://app.bountysource.com/issues/109316302-tracking-for-integration-testing)

**Comment by Tedionwe** [comment]
hi please this bounty still on

**Comment by gnunicorn** [comment]
@Tedionwe not really. with https://github.com/effektio/effektio/pull/174 we have all that covered more or less.
